# coding: utf-8

"""
    Metal API

    This is the API for Equinix Metal Product. Interact with your devices, user account, and projects.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@equinixmetal.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import metal
from models.usages_api import UsagesApi  # noqa: E501
from metal.rest import ApiException


class TestUsagesApi(unittest.TestCase):
    """UsagesApi unit test stubs"""

    def setUp(self):
        self.api = models.usages_api.UsagesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_find_device_usages(self):
        """Test case for find_device_usages

        Retrieve all usages for device  # noqa: E501
        """
        pass

    def test_find_project_usage(self):
        """Test case for find_project_usage

        Retrieve all usages for project  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
