# coding: utf-8

"""
    Metal API

    This is the API for Equinix Metal Product. Interact with your devices, user account, and projects.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@equinixmetal.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import metal
from models.transfer_requests_api import TransferRequestsApi  # noqa: E501
from metal.rest import ApiException


class TestTransferRequestsApi(unittest.TestCase):
    """TransferRequestsApi unit test stubs"""

    def setUp(self):
        self.api = models.transfer_requests_api.TransferRequestsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_accept_transfer_request(self):
        """Test case for accept_transfer_request

        Accept a transfer request  # noqa: E501
        """
        pass

    def test_create_transfer_request(self):
        """Test case for create_transfer_request

        Create a transfer request  # noqa: E501
        """
        pass

    def test_decline_transfer_request(self):
        """Test case for decline_transfer_request

        Decline a transfer request  # noqa: E501
        """
        pass

    def test_find_organization_transfers(self):
        """Test case for find_organization_transfers

        Retrieve all project transfer requests from or to an organization  # noqa: E501
        """
        pass

    def test_find_transfer_request_by_id(self):
        """Test case for find_transfer_request_by_id

        View a transfer request  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
