"""
    Metal API

    This is the API for Equinix Metal Product. Interact with your devices, user account, and projects.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@equinixmetal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import metal
from metal.model.entitlement_input import EntitlementInput


class TestEntitlementInput(unittest.TestCase):
    """EntitlementInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEntitlementInput(self):
        """Test EntitlementInput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EntitlementInput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
