"""
    Metal API

    This is the API for Equinix Metal Product. Interact with your devices, user account, and projects.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@equinixmetal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import metal
from metal.model.staff_facility_little import StaffFacilityLittle
from metal.model.staff_metro_little import StaffMetroLittle
from metal.model.staff_port import StaffPort
globals()['StaffFacilityLittle'] = StaffFacilityLittle
globals()['StaffMetroLittle'] = StaffMetroLittle
globals()['StaffPort'] = StaffPort
from metal.model.staff_ip_address import StaffIpAddress


class TestStaffIpAddress(unittest.TestCase):
    """StaffIpAddress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStaffIpAddress(self):
        """Test StaffIpAddress"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StaffIpAddress()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
