# coding: utf-8

"""
    Metal API

    This is the API for Equinix Metal Product. Interact with your devices, user account, and projects.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@equinixmetal.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import metal
from models.events_api import EventsApi  # noqa: E501
from metal.rest import ApiException


class TestEventsApi(unittest.TestCase):
    """EventsApi unit test stubs"""

    def setUp(self):
        self.api = models.events_api.EventsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_find_connection_events(self):
        """Test case for find_connection_events

        Retrieve connection events  # noqa: E501
        """
        pass

    def test_find_connection_port_events(self):
        """Test case for find_connection_port_events

        Retrieve connection port events  # noqa: E501
        """
        pass

    def test_find_device_events(self):
        """Test case for find_device_events

        Retrieve device's events  # noqa: E501
        """
        pass

    def test_find_event_by_id(self):
        """Test case for find_event_by_id

        Retrieve an event  # noqa: E501
        """
        pass

    def test_find_events(self):
        """Test case for find_events

        Retrieve current user's events  # noqa: E501
        """
        pass

    def test_find_organization_events(self):
        """Test case for find_organization_events

        Retrieve organization's events  # noqa: E501
        """
        pass

    def test_find_project_events(self):
        """Test case for find_project_events

        Retrieve project's events  # noqa: E501
        """
        pass

    def test_find_virtual_circuit_events(self):
        """Test case for find_virtual_circuit_events

        Retrieve connection events  # noqa: E501
        """
        pass

    def test_find_volume_events(self):
        """Test case for find_volume_events

        Retrieve volume's events  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
