"""
    Metal API

    This is the API for Equinix Metal Product. Interact with your devices, user account, and projects.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@equinixmetal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import metal
from metal.model.email_input import EmailInput
globals()['EmailInput'] = EmailInput
from metal.model.user_create_input import UserCreateInput


class TestUserCreateInput(unittest.TestCase):
    """UserCreateInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserCreateInput(self):
        """Test UserCreateInput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserCreateInput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
