"""
    Metal API

    This is the API for Equinix Metal Product. Interact with your devices, user account, and projects.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@equinixmetal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import metal
from metal.model.volume_update_input import VolumeUpdateInput


class TestVolumeUpdateInput(unittest.TestCase):
    """VolumeUpdateInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVolumeUpdateInput(self):
        """Test VolumeUpdateInput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VolumeUpdateInput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
