"""
    Metal API

    This is the API for Equinix Metal Product. Interact with your devices, user account, and projects.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@equinixmetal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import metal
from metal.model.facility import Facility
from metal.model.ip_assignment import IPAssignment
globals()['Facility'] = Facility
globals()['IPAssignment'] = IPAssignment
from metal.model.ip_reservation import IPReservation


class TestIPReservation(unittest.TestCase):
    """IPReservation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIPReservation(self):
        """Test IPReservation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IPReservation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
