# coding: utf-8

"""
    Metal API

    This is the API for Equinix Metal Product. Interact with your devices, user account, and projects.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@equinixmetal.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import metal
from models.projects_api import ProjectsApi  # noqa: E501
from metal.rest import ApiException


class TestProjectsApi(unittest.TestCase):
    """ProjectsApi unit test stubs"""

    def setUp(self):
        self.api = models.projects_api.ProjectsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_device(self):
        """Test case for create_device

        Create a device  # noqa: E501
        """
        pass

    def test_create_license(self):
        """Test case for create_license

        Create a License  # noqa: E501
        """
        pass

    def test_create_organization_project(self):
        """Test case for create_organization_project

        Create a project for the organization  # noqa: E501
        """
        pass

    def test_create_project(self):
        """Test case for create_project

        Create a project  # noqa: E501
        """
        pass

    def test_create_project_invitation(self):
        """Test case for create_project_invitation

        Create an invitation for a project  # noqa: E501
        """
        pass

    def test_create_project_ssh_key(self):
        """Test case for create_project_ssh_key

        Create a ssh key for the given project  # noqa: E501
        """
        pass

    def test_create_spot_market_request(self):
        """Test case for create_spot_market_request

        Create a spot market request  # noqa: E501
        """
        pass

    def test_create_transfer_request(self):
        """Test case for create_transfer_request

        Create a transfer request  # noqa: E501
        """
        pass

    def test_create_virtual_network(self):
        """Test case for create_virtual_network

        Create an virtual network  # noqa: E501
        """
        pass

    def test_delete_project(self):
        """Test case for delete_project

        Delete the project  # noqa: E501
        """
        pass

    def test_find_batches_by_project(self):
        """Test case for find_batches_by_project

        Retrieve all batches by project  # noqa: E501
        """
        pass

    def test_find_bgp_config_by_project(self):
        """Test case for find_bgp_config_by_project

        Retrieve a bgp config  # noqa: E501
        """
        pass

    def test_find_device_ssh_keys(self):
        """Test case for find_device_ssh_keys

        Retrieve a device's ssh keys  # noqa: E501
        """
        pass

    def test_find_facilities_by_project(self):
        """Test case for find_facilities_by_project

        Retrieve all facilities visible by the project  # noqa: E501
        """
        pass

    def test_find_ip_reservation_customdata(self):
        """Test case for find_ip_reservation_customdata

        Retrieve the custom metadata of an IP Reservation  # noqa: E501
        """
        pass

    def test_find_ip_reservations(self):
        """Test case for find_ip_reservations

        Retrieve all ip reservations  # noqa: E501
        """
        pass

    def test_find_organization_projects(self):
        """Test case for find_organization_projects

        Retrieve all projects of an organization  # noqa: E501
        """
        pass

    def test_find_plans_by_project(self):
        """Test case for find_plans_by_project

        Retrieve all plans visible by the project  # noqa: E501
        """
        pass

    def test_find_project_bgp_sessions(self):
        """Test case for find_project_bgp_sessions

        Retrieve all BGP sessions for project  # noqa: E501
        """
        pass

    def test_find_project_by_id(self):
        """Test case for find_project_by_id

        Retrieve a project  # noqa: E501
        """
        pass

    def test_find_project_customdata(self):
        """Test case for find_project_customdata

        Retrieve the custom metadata of a project  # noqa: E501
        """
        pass

    def test_find_project_devices(self):
        """Test case for find_project_devices

        Retrieve all devices of a project  # noqa: E501
        """
        pass

    def test_find_project_events(self):
        """Test case for find_project_events

        Retrieve project's events  # noqa: E501
        """
        pass

    def test_find_project_hardware_reservations(self):
        """Test case for find_project_hardware_reservations

        Retrieve all hardware reservations for a given project  # noqa: E501
        """
        pass

    def test_find_project_invitations(self):
        """Test case for find_project_invitations

        Retrieve project invitations  # noqa: E501
        """
        pass

    def test_find_project_licenses(self):
        """Test case for find_project_licenses

        Retrieve all licenses  # noqa: E501
        """
        pass

    def test_find_project_memberships(self):
        """Test case for find_project_memberships

        Retrieve project memberships  # noqa: E501
        """
        pass

    def test_find_project_ssh_keys(self):
        """Test case for find_project_ssh_keys

        Retrieve a project's ssh keys  # noqa: E501
        """
        pass

    def test_find_projects(self):
        """Test case for find_projects

        Retrieve all projects  # noqa: E501
        """
        pass

    def test_find_virtual_networks(self):
        """Test case for find_virtual_networks

        Retrieve all virtual networks  # noqa: E501
        """
        pass

    def test_list_spot_market_requests(self):
        """Test case for list_spot_market_requests

        List spot market requests  # noqa: E501
        """
        pass

    def test_request_bgp_config(self):
        """Test case for request_bgp_config

        Requesting bgp config  # noqa: E501
        """
        pass

    def test_request_ip_reservation(self):
        """Test case for request_ip_reservation

        Requesting IP reservations  # noqa: E501
        """
        pass

    def test_update_project(self):
        """Test case for update_project

        Update the project  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
