=begin
#Metal API

#This is the API for Equinix Metal Product. Interact with your devices, user account, and projects.

The version of the OpenAPI document: 1.0.0
Contact: support@equinixmetal.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::OperatingSystemVersionsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'OperatingSystemVersionsApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::OperatingSystemVersionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OperatingSystemVersionsApi' do
    it 'should create an instance of OperatingSystemVersionsApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::OperatingSystemVersionsApi)
    end
  end

  # unit tests for find_operating_system_version
  # Retrieve all operating system versions
  # Provides a listing of available operating system versions.
  # @param [Hash] opts the optional parameters
  # @return [Array<OperatingSystem>]
  describe 'find_operating_system_version test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
