# coding: utf-8

"""
    Metal API

    This is the API for Equinix Metal Product. Interact with your devices, user account, and projects.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@equinixmetal.com
    Generated by: https://openapi-generator.tech
"""


import inspect
import pprint
import re  # noqa: F401
import six

from metal.configuration import Configuration


class VirtualCircuitUpdateInput(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'description': 'str',
        'name': 'str',
        'speed': 'str',
        'tags': 'list[str]',
        'vnid': 'str'
    }

    attribute_map = {
        'description': 'description',
        'name': 'name',
        'speed': 'speed',
        'tags': 'tags',
        'vnid': 'vnid'
    }

    def __init__(self, description=None, name=None, speed=None, tags=None, vnid=None, local_vars_configuration=None):  # noqa: E501
        """VirtualCircuitUpdateInput - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._description = None
        self._name = None
        self._speed = None
        self._tags = None
        self._vnid = None
        self.discriminator = None

        if description is not None:
            self.description = description
        if name is not None:
            self.name = name
        if speed is not None:
            self.speed = speed
        if tags is not None:
            self.tags = tags
        if vnid is not None:
            self.vnid = vnid

    @property
    def description(self):
        """Gets the description of this VirtualCircuitUpdateInput.  # noqa: E501


        :return: The description of this VirtualCircuitUpdateInput.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this VirtualCircuitUpdateInput.


        :param description: The description of this VirtualCircuitUpdateInput.  # noqa: E501
        :type description: str
        """

        self._description = description

    @property
    def name(self):
        """Gets the name of this VirtualCircuitUpdateInput.  # noqa: E501


        :return: The name of this VirtualCircuitUpdateInput.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this VirtualCircuitUpdateInput.


        :param name: The name of this VirtualCircuitUpdateInput.  # noqa: E501
        :type name: str
        """

        self._name = name

    @property
    def speed(self):
        """Gets the speed of this VirtualCircuitUpdateInput.  # noqa: E501


        :return: The speed of this VirtualCircuitUpdateInput.  # noqa: E501
        :rtype: str
        """
        return self._speed

    @speed.setter
    def speed(self, speed):
        """Sets the speed of this VirtualCircuitUpdateInput.


        :param speed: The speed of this VirtualCircuitUpdateInput.  # noqa: E501
        :type speed: str
        """

        self._speed = speed

    @property
    def tags(self):
        """Gets the tags of this VirtualCircuitUpdateInput.  # noqa: E501


        :return: The tags of this VirtualCircuitUpdateInput.  # noqa: E501
        :rtype: list[str]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this VirtualCircuitUpdateInput.


        :param tags: The tags of this VirtualCircuitUpdateInput.  # noqa: E501
        :type tags: list[str]
        """

        self._tags = tags

    @property
    def vnid(self):
        """Gets the vnid of this VirtualCircuitUpdateInput.  # noqa: E501

        A Virtual Network record UUID or the VNID of a Virtual Network in your project.  # noqa: E501

        :return: The vnid of this VirtualCircuitUpdateInput.  # noqa: E501
        :rtype: str
        """
        return self._vnid

    @vnid.setter
    def vnid(self, vnid):
        """Sets the vnid of this VirtualCircuitUpdateInput.

        A Virtual Network record UUID or the VNID of a Virtual Network in your project.  # noqa: E501

        :param vnid: The vnid of this VirtualCircuitUpdateInput.  # noqa: E501
        :type vnid: str
        """

        self._vnid = vnid

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = inspect.getargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VirtualCircuitUpdateInput):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, VirtualCircuitUpdateInput):
            return True

        return self.to_dict() != other.to_dict()
