# coding: utf-8

"""
    Metal API

    This is the API for Equinix Metal Product. Interact with your devices, user account, and projects.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@equinixmetal.com
    Generated by: https://openapi-generator.tech
"""


import inspect
import pprint
import re  # noqa: F401
import six

from metal.configuration import Configuration


class VirtualCircuitCreateInput(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'description': 'str',
        'name': 'str',
        'speed': 'int',
        'tags': 'list[str]',
        'vnid': 'str',
        'nni_vlan': 'int',
        'project': 'str'
    }

    attribute_map = {
        'description': 'description',
        'name': 'name',
        'speed': 'speed',
        'tags': 'tags',
        'vnid': 'vnid',
        'nni_vlan': 'nni_vlan',
        'project': 'project'
    }

    def __init__(self, description=None, name=None, speed=None, tags=None, vnid=None, nni_vlan=None, project=None, local_vars_configuration=None):  # noqa: E501
        """VirtualCircuitCreateInput - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._description = None
        self._name = None
        self._speed = None
        self._tags = None
        self._vnid = None
        self._nni_vlan = None
        self._project = None
        self.discriminator = None

        if description is not None:
            self.description = description
        if name is not None:
            self.name = name
        if speed is not None:
            self.speed = speed
        if tags is not None:
            self.tags = tags
        if vnid is not None:
            self.vnid = vnid
        if nni_vlan is not None:
            self.nni_vlan = nni_vlan
        if project is not None:
            self.project = project

    @property
    def description(self):
        """Gets the description of this VirtualCircuitCreateInput.  # noqa: E501


        :return: The description of this VirtualCircuitCreateInput.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this VirtualCircuitCreateInput.


        :param description: The description of this VirtualCircuitCreateInput.  # noqa: E501
        :type description: str
        """

        self._description = description

    @property
    def name(self):
        """Gets the name of this VirtualCircuitCreateInput.  # noqa: E501


        :return: The name of this VirtualCircuitCreateInput.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this VirtualCircuitCreateInput.


        :param name: The name of this VirtualCircuitCreateInput.  # noqa: E501
        :type name: str
        """

        self._name = name

    @property
    def speed(self):
        """Gets the speed of this VirtualCircuitCreateInput.  # noqa: E501

        speed can be passed as integer number representing bps speed or string (e.g. '52m' or '100g' or '4 gbps')  # noqa: E501

        :return: The speed of this VirtualCircuitCreateInput.  # noqa: E501
        :rtype: int
        """
        return self._speed

    @speed.setter
    def speed(self, speed):
        """Sets the speed of this VirtualCircuitCreateInput.

        speed can be passed as integer number representing bps speed or string (e.g. '52m' or '100g' or '4 gbps')  # noqa: E501

        :param speed: The speed of this VirtualCircuitCreateInput.  # noqa: E501
        :type speed: int
        """

        self._speed = speed

    @property
    def tags(self):
        """Gets the tags of this VirtualCircuitCreateInput.  # noqa: E501


        :return: The tags of this VirtualCircuitCreateInput.  # noqa: E501
        :rtype: list[str]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this VirtualCircuitCreateInput.


        :param tags: The tags of this VirtualCircuitCreateInput.  # noqa: E501
        :type tags: list[str]
        """

        self._tags = tags

    @property
    def vnid(self):
        """Gets the vnid of this VirtualCircuitCreateInput.  # noqa: E501

        A Virtual Network record UUID or the VNID of a Virtual Network in your project (sent as integer).  # noqa: E501

        :return: The vnid of this VirtualCircuitCreateInput.  # noqa: E501
        :rtype: str
        """
        return self._vnid

    @vnid.setter
    def vnid(self, vnid):
        """Sets the vnid of this VirtualCircuitCreateInput.

        A Virtual Network record UUID or the VNID of a Virtual Network in your project (sent as integer).  # noqa: E501

        :param vnid: The vnid of this VirtualCircuitCreateInput.  # noqa: E501
        :type vnid: str
        """

        self._vnid = vnid

    @property
    def nni_vlan(self):
        """Gets the nni_vlan of this VirtualCircuitCreateInput.  # noqa: E501


        :return: The nni_vlan of this VirtualCircuitCreateInput.  # noqa: E501
        :rtype: int
        """
        return self._nni_vlan

    @nni_vlan.setter
    def nni_vlan(self, nni_vlan):
        """Sets the nni_vlan of this VirtualCircuitCreateInput.


        :param nni_vlan: The nni_vlan of this VirtualCircuitCreateInput.  # noqa: E501
        :type nni_vlan: int
        """
        if (self.local_vars_configuration.client_side_validation and
                nni_vlan is not None and nni_vlan > 4094):  # noqa: E501
            raise ValueError("Invalid value for `nni_vlan`, must be a value less than or equal to `4094`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                nni_vlan is not None and nni_vlan < 2):  # noqa: E501
            raise ValueError("Invalid value for `nni_vlan`, must be a value greater than or equal to `2`")  # noqa: E501

        self._nni_vlan = nni_vlan

    @property
    def project(self):
        """Gets the project of this VirtualCircuitCreateInput.  # noqa: E501


        :return: The project of this VirtualCircuitCreateInput.  # noqa: E501
        :rtype: str
        """
        return self._project

    @project.setter
    def project(self, project):
        """Sets the project of this VirtualCircuitCreateInput.


        :param project: The project of this VirtualCircuitCreateInput.  # noqa: E501
        :type project: str
        """

        self._project = project

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = inspect.getargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VirtualCircuitCreateInput):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, VirtualCircuitCreateInput):
            return True

        return self.to_dict() != other.to_dict()
