# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from metal.types.base_model_ import Model
from metal import util


class DeviceUpdateInput(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, hostname=None, description=None, billing_cycle=None, userdata=None, locked=None, tags=None, always_pxe=None, ipxe_script_url=None, spot_instance=None, customdata=None):  # noqa: E501
        """DeviceUpdateInput - a model defined in OpenAPI

        :param hostname: The hostname of this DeviceUpdateInput.  # noqa: E501
        :type hostname: str
        :param description: The description of this DeviceUpdateInput.  # noqa: E501
        :type description: str
        :param billing_cycle: The billing_cycle of this DeviceUpdateInput.  # noqa: E501
        :type billing_cycle: str
        :param userdata: The userdata of this DeviceUpdateInput.  # noqa: E501
        :type userdata: str
        :param locked: The locked of this DeviceUpdateInput.  # noqa: E501
        :type locked: bool
        :param tags: The tags of this DeviceUpdateInput.  # noqa: E501
        :type tags: List[str]
        :param always_pxe: The always_pxe of this DeviceUpdateInput.  # noqa: E501
        :type always_pxe: bool
        :param ipxe_script_url: The ipxe_script_url of this DeviceUpdateInput.  # noqa: E501
        :type ipxe_script_url: str
        :param spot_instance: The spot_instance of this DeviceUpdateInput.  # noqa: E501
        :type spot_instance: bool
        :param customdata: The customdata of this DeviceUpdateInput.  # noqa: E501
        :type customdata: object
        """
        self.openapi_types = {
            'hostname': str,
            'description': str,
            'billing_cycle': str,
            'userdata': str,
            'locked': bool,
            'tags': List[str],
            'always_pxe': bool,
            'ipxe_script_url': str,
            'spot_instance': bool,
            'customdata': object
        }

        self.attribute_map = {
            'hostname': 'hostname',
            'description': 'description',
            'billing_cycle': 'billing_cycle',
            'userdata': 'userdata',
            'locked': 'locked',
            'tags': 'tags',
            'always_pxe': 'always_pxe',
            'ipxe_script_url': 'ipxe_script_url',
            'spot_instance': 'spot_instance',
            'customdata': 'customdata'
        }

        self._hostname = hostname
        self._description = description
        self._billing_cycle = billing_cycle
        self._userdata = userdata
        self._locked = locked
        self._tags = tags
        self._always_pxe = always_pxe
        self._ipxe_script_url = ipxe_script_url
        self._spot_instance = spot_instance
        self._customdata = customdata

    @classmethod
    def from_dict(cls, dikt) -> 'DeviceUpdateInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DeviceUpdateInput of this DeviceUpdateInput.  # noqa: E501
        :rtype: DeviceUpdateInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def hostname(self):
        """Gets the hostname of this DeviceUpdateInput.


        :return: The hostname of this DeviceUpdateInput.
        :rtype: str
        """
        return self._hostname

    @hostname.setter
    def hostname(self, hostname):
        """Sets the hostname of this DeviceUpdateInput.


        :param hostname: The hostname of this DeviceUpdateInput.
        :type hostname: str
        """

        self._hostname = hostname

    @property
    def description(self):
        """Gets the description of this DeviceUpdateInput.


        :return: The description of this DeviceUpdateInput.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this DeviceUpdateInput.


        :param description: The description of this DeviceUpdateInput.
        :type description: str
        """

        self._description = description

    @property
    def billing_cycle(self):
        """Gets the billing_cycle of this DeviceUpdateInput.


        :return: The billing_cycle of this DeviceUpdateInput.
        :rtype: str
        """
        return self._billing_cycle

    @billing_cycle.setter
    def billing_cycle(self, billing_cycle):
        """Sets the billing_cycle of this DeviceUpdateInput.


        :param billing_cycle: The billing_cycle of this DeviceUpdateInput.
        :type billing_cycle: str
        """

        self._billing_cycle = billing_cycle

    @property
    def userdata(self):
        """Gets the userdata of this DeviceUpdateInput.


        :return: The userdata of this DeviceUpdateInput.
        :rtype: str
        """
        return self._userdata

    @userdata.setter
    def userdata(self, userdata):
        """Sets the userdata of this DeviceUpdateInput.


        :param userdata: The userdata of this DeviceUpdateInput.
        :type userdata: str
        """

        self._userdata = userdata

    @property
    def locked(self):
        """Gets the locked of this DeviceUpdateInput.


        :return: The locked of this DeviceUpdateInput.
        :rtype: bool
        """
        return self._locked

    @locked.setter
    def locked(self, locked):
        """Sets the locked of this DeviceUpdateInput.


        :param locked: The locked of this DeviceUpdateInput.
        :type locked: bool
        """

        self._locked = locked

    @property
    def tags(self):
        """Gets the tags of this DeviceUpdateInput.


        :return: The tags of this DeviceUpdateInput.
        :rtype: List[str]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this DeviceUpdateInput.


        :param tags: The tags of this DeviceUpdateInput.
        :type tags: List[str]
        """

        self._tags = tags

    @property
    def always_pxe(self):
        """Gets the always_pxe of this DeviceUpdateInput.


        :return: The always_pxe of this DeviceUpdateInput.
        :rtype: bool
        """
        return self._always_pxe

    @always_pxe.setter
    def always_pxe(self, always_pxe):
        """Sets the always_pxe of this DeviceUpdateInput.


        :param always_pxe: The always_pxe of this DeviceUpdateInput.
        :type always_pxe: bool
        """

        self._always_pxe = always_pxe

    @property
    def ipxe_script_url(self):
        """Gets the ipxe_script_url of this DeviceUpdateInput.


        :return: The ipxe_script_url of this DeviceUpdateInput.
        :rtype: str
        """
        return self._ipxe_script_url

    @ipxe_script_url.setter
    def ipxe_script_url(self, ipxe_script_url):
        """Sets the ipxe_script_url of this DeviceUpdateInput.


        :param ipxe_script_url: The ipxe_script_url of this DeviceUpdateInput.
        :type ipxe_script_url: str
        """

        self._ipxe_script_url = ipxe_script_url

    @property
    def spot_instance(self):
        """Gets the spot_instance of this DeviceUpdateInput.


        :return: The spot_instance of this DeviceUpdateInput.
        :rtype: bool
        """
        return self._spot_instance

    @spot_instance.setter
    def spot_instance(self, spot_instance):
        """Sets the spot_instance of this DeviceUpdateInput.


        :param spot_instance: The spot_instance of this DeviceUpdateInput.
        :type spot_instance: bool
        """

        self._spot_instance = spot_instance

    @property
    def customdata(self):
        """Gets the customdata of this DeviceUpdateInput.


        :return: The customdata of this DeviceUpdateInput.
        :rtype: object
        """
        return self._customdata

    @customdata.setter
    def customdata(self, customdata):
        """Sets the customdata of this DeviceUpdateInput.


        :param customdata: The customdata of this DeviceUpdateInput.
        :type customdata: object
        """

        self._customdata = customdata
