# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from metal.types.base_model_ import Model
from metal.types.device_usage import DeviceUsage
from metal import util

from metal.types.device_usage import DeviceUsage  # noqa: E501

class DeviceUsageList(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, usages=None):  # noqa: E501
        """DeviceUsageList - a model defined in OpenAPI

        :param usages: The usages of this DeviceUsageList.  # noqa: E501
        :type usages: List[DeviceUsage]
        """
        self.openapi_types = {
            'usages': List[DeviceUsage]
        }

        self.attribute_map = {
            'usages': 'usages'
        }

        self._usages = usages

    @classmethod
    def from_dict(cls, dikt) -> 'DeviceUsageList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DeviceUsageList of this DeviceUsageList.  # noqa: E501
        :rtype: DeviceUsageList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def usages(self):
        """Gets the usages of this DeviceUsageList.


        :return: The usages of this DeviceUsageList.
        :rtype: List[DeviceUsage]
        """
        return self._usages

    @usages.setter
    def usages(self, usages):
        """Sets the usages of this DeviceUsageList.


        :param usages: The usages of this DeviceUsageList.
        :type usages: List[DeviceUsage]
        """

        self._usages = usages
