# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from metal.types.base_model_ import Model
from metal import util


class GlobalBgpRange(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, address_family=None, range=None, href=None):  # noqa: E501
        """GlobalBgpRange - a model defined in OpenAPI

        :param id: The id of this GlobalBgpRange.  # noqa: E501
        :type id: str
        :param address_family: The address_family of this GlobalBgpRange.  # noqa: E501
        :type address_family: int
        :param range: The range of this GlobalBgpRange.  # noqa: E501
        :type range: str
        :param href: The href of this GlobalBgpRange.  # noqa: E501
        :type href: str
        """
        self.openapi_types = {
            'id': str,
            'address_family': int,
            'range': str,
            'href': str
        }

        self.attribute_map = {
            'id': 'id',
            'address_family': 'address_family',
            'range': 'range',
            'href': 'href'
        }

        self._id = id
        self._address_family = address_family
        self._range = range
        self._href = href

    @classmethod
    def from_dict(cls, dikt) -> 'GlobalBgpRange':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GlobalBgpRange of this GlobalBgpRange.  # noqa: E501
        :rtype: GlobalBgpRange
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this GlobalBgpRange.


        :return: The id of this GlobalBgpRange.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this GlobalBgpRange.


        :param id: The id of this GlobalBgpRange.
        :type id: str
        """

        self._id = id

    @property
    def address_family(self):
        """Gets the address_family of this GlobalBgpRange.


        :return: The address_family of this GlobalBgpRange.
        :rtype: int
        """
        return self._address_family

    @address_family.setter
    def address_family(self, address_family):
        """Sets the address_family of this GlobalBgpRange.


        :param address_family: The address_family of this GlobalBgpRange.
        :type address_family: int
        """

        self._address_family = address_family

    @property
    def range(self):
        """Gets the range of this GlobalBgpRange.


        :return: The range of this GlobalBgpRange.
        :rtype: str
        """
        return self._range

    @range.setter
    def range(self, range):
        """Sets the range of this GlobalBgpRange.


        :param range: The range of this GlobalBgpRange.
        :type range: str
        """

        self._range = range

    @property
    def href(self):
        """Gets the href of this GlobalBgpRange.


        :return: The href of this GlobalBgpRange.
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href):
        """Sets the href of this GlobalBgpRange.


        :param href: The href of this GlobalBgpRange.
        :type href: str
        """

        self._href = href
