# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from metal.types.base_model_ import Model
from metal.types.href import Href
from metal import util

from metal.types.href import Href  # noqa: E501

class Invitation(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, roles=None, invitee=None, created_at=None, updated_at=None, invited_by=None, organization=None, projects_ids=None, invitation=None, href=None):  # noqa: E501
        """Invitation - a model defined in OpenAPI

        :param id: The id of this Invitation.  # noqa: E501
        :type id: str
        :param roles: The roles of this Invitation.  # noqa: E501
        :type roles: List[str]
        :param invitee: The invitee of this Invitation.  # noqa: E501
        :type invitee: str
        :param created_at: The created_at of this Invitation.  # noqa: E501
        :type created_at: datetime
        :param updated_at: The updated_at of this Invitation.  # noqa: E501
        :type updated_at: datetime
        :param invited_by: The invited_by of this Invitation.  # noqa: E501
        :type invited_by: Href
        :param organization: The organization of this Invitation.  # noqa: E501
        :type organization: Href
        :param projects_ids: The projects_ids of this Invitation.  # noqa: E501
        :type projects_ids: List[str]
        :param invitation: The invitation of this Invitation.  # noqa: E501
        :type invitation: Href
        :param href: The href of this Invitation.  # noqa: E501
        :type href: str
        """
        self.openapi_types = {
            'id': str,
            'roles': List[str],
            'invitee': str,
            'created_at': datetime,
            'updated_at': datetime,
            'invited_by': Href,
            'organization': Href,
            'projects_ids': List[str],
            'invitation': Href,
            'href': str
        }

        self.attribute_map = {
            'id': 'id',
            'roles': 'roles',
            'invitee': 'invitee',
            'created_at': 'created_at',
            'updated_at': 'updated_at',
            'invited_by': 'invited_by',
            'organization': 'organization',
            'projects_ids': 'projects_ids',
            'invitation': 'invitation',
            'href': 'href'
        }

        self._id = id
        self._roles = roles
        self._invitee = invitee
        self._created_at = created_at
        self._updated_at = updated_at
        self._invited_by = invited_by
        self._organization = organization
        self._projects_ids = projects_ids
        self._invitation = invitation
        self._href = href

    @classmethod
    def from_dict(cls, dikt) -> 'Invitation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Invitation of this Invitation.  # noqa: E501
        :rtype: Invitation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this Invitation.


        :return: The id of this Invitation.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Invitation.


        :param id: The id of this Invitation.
        :type id: str
        """

        self._id = id

    @property
    def roles(self):
        """Gets the roles of this Invitation.


        :return: The roles of this Invitation.
        :rtype: List[str]
        """
        return self._roles

    @roles.setter
    def roles(self, roles):
        """Sets the roles of this Invitation.


        :param roles: The roles of this Invitation.
        :type roles: List[str]
        """

        self._roles = roles

    @property
    def invitee(self):
        """Gets the invitee of this Invitation.


        :return: The invitee of this Invitation.
        :rtype: str
        """
        return self._invitee

    @invitee.setter
    def invitee(self, invitee):
        """Sets the invitee of this Invitation.


        :param invitee: The invitee of this Invitation.
        :type invitee: str
        """

        self._invitee = invitee

    @property
    def created_at(self):
        """Gets the created_at of this Invitation.


        :return: The created_at of this Invitation.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this Invitation.


        :param created_at: The created_at of this Invitation.
        :type created_at: datetime
        """

        self._created_at = created_at

    @property
    def updated_at(self):
        """Gets the updated_at of this Invitation.


        :return: The updated_at of this Invitation.
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this Invitation.


        :param updated_at: The updated_at of this Invitation.
        :type updated_at: datetime
        """

        self._updated_at = updated_at

    @property
    def invited_by(self):
        """Gets the invited_by of this Invitation.


        :return: The invited_by of this Invitation.
        :rtype: Href
        """
        return self._invited_by

    @invited_by.setter
    def invited_by(self, invited_by):
        """Sets the invited_by of this Invitation.


        :param invited_by: The invited_by of this Invitation.
        :type invited_by: Href
        """

        self._invited_by = invited_by

    @property
    def organization(self):
        """Gets the organization of this Invitation.


        :return: The organization of this Invitation.
        :rtype: Href
        """
        return self._organization

    @organization.setter
    def organization(self, organization):
        """Sets the organization of this Invitation.


        :param organization: The organization of this Invitation.
        :type organization: Href
        """

        self._organization = organization

    @property
    def projects_ids(self):
        """Gets the projects_ids of this Invitation.


        :return: The projects_ids of this Invitation.
        :rtype: List[str]
        """
        return self._projects_ids

    @projects_ids.setter
    def projects_ids(self, projects_ids):
        """Sets the projects_ids of this Invitation.


        :param projects_ids: The projects_ids of this Invitation.
        :type projects_ids: List[str]
        """

        self._projects_ids = projects_ids

    @property
    def invitation(self):
        """Gets the invitation of this Invitation.


        :return: The invitation of this Invitation.
        :rtype: Href
        """
        return self._invitation

    @invitation.setter
    def invitation(self, invitation):
        """Sets the invitation of this Invitation.


        :param invitation: The invitation of this Invitation.
        :type invitation: Href
        """

        self._invitation = invitation

    @property
    def href(self):
        """Gets the href of this Invitation.


        :return: The href of this Invitation.
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href):
        """Sets the href of this Invitation.


        :param href: The href of this Invitation.
        :type href: str
        """

        self._href = href
