# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from metal.types.base_model_ import Model
from metal.types.project_usage import ProjectUsage
from metal import util

from metal.types.project_usage import ProjectUsage  # noqa: E501

class ProjectUsageList(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, usages=None):  # noqa: E501
        """ProjectUsageList - a model defined in OpenAPI

        :param usages: The usages of this ProjectUsageList.  # noqa: E501
        :type usages: List[ProjectUsage]
        """
        self.openapi_types = {
            'usages': List[ProjectUsage]
        }

        self.attribute_map = {
            'usages': 'usages'
        }

        self._usages = usages

    @classmethod
    def from_dict(cls, dikt) -> 'ProjectUsageList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProjectUsageList of this ProjectUsageList.  # noqa: E501
        :rtype: ProjectUsageList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def usages(self):
        """Gets the usages of this ProjectUsageList.


        :return: The usages of this ProjectUsageList.
        :rtype: List[ProjectUsage]
        """
        return self._usages

    @usages.setter
    def usages(self, usages):
        """Sets the usages of this ProjectUsageList.


        :param usages: The usages of this ProjectUsageList.
        :type usages: List[ProjectUsage]
        """

        self._usages = usages
