# coding: utf-8

"""
    Metal API

    This is the API for Equinix Metal Product. Interact with your devices, user account, and projects.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@equinixmetal.com
    Generated by: https://openapi-generator.tech
"""


import inspect
import pprint
import re  # noqa: F401
import six

from metal.configuration import Configuration


class RackmountInput(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'top_slot': 'str',
        'type': 'str'
    }

    attribute_map = {
        'top_slot': 'top_slot',
        'type': 'type'
    }

    def __init__(self, top_slot=None, type=None, local_vars_configuration=None):  # noqa: E501
        """RackmountInput - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._top_slot = None
        self._type = None
        self.discriminator = None

        if top_slot is not None:
            self.top_slot = top_slot
        if type is not None:
            self.type = type

    @property
    def top_slot(self):
        """Gets the top_slot of this RackmountInput.  # noqa: E501


        :return: The top_slot of this RackmountInput.  # noqa: E501
        :rtype: str
        """
        return self._top_slot

    @top_slot.setter
    def top_slot(self, top_slot):
        """Sets the top_slot of this RackmountInput.


        :param top_slot: The top_slot of this RackmountInput.  # noqa: E501
        :type top_slot: str
        """

        self._top_slot = top_slot

    @property
    def type(self):
        """Gets the type of this RackmountInput.  # noqa: E501


        :return: The type of this RackmountInput.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this RackmountInput.


        :param type: The type of this RackmountInput.  # noqa: E501
        :type type: str
        """

        self._type = type

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = inspect.getargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RackmountInput):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, RackmountInput):
            return True

        return self.to_dict() != other.to_dict()
