# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from metal.types.base_model_ import Model
from metal.types.region import Region
from metal import util

from metal.types.region import Region  # noqa: E501

class RegionsList(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, regions=None):  # noqa: E501
        """RegionsList - a model defined in OpenAPI

        :param regions: The regions of this RegionsList.  # noqa: E501
        :type regions: List[Region]
        """
        self.openapi_types = {
            'regions': List[Region]
        }

        self.attribute_map = {
            'regions': 'regions'
        }

        self._regions = regions

    @classmethod
    def from_dict(cls, dikt) -> 'RegionsList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RegionsList of this RegionsList.  # noqa: E501
        :rtype: RegionsList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def regions(self):
        """Gets the regions of this RegionsList.


        :return: The regions of this RegionsList.
        :rtype: List[Region]
        """
        return self._regions

    @regions.setter
    def regions(self, regions):
        """Sets the regions of this RegionsList.


        :param regions: The regions of this RegionsList.
        :type regions: List[Region]
        """

        self._regions = regions
