# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from metal.types.base_model_ import Model
from metal import util


class SpotPricesDatapoints(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, datapoints=None):  # noqa: E501
        """SpotPricesDatapoints - a model defined in OpenAPI

        :param datapoints: The datapoints of this SpotPricesDatapoints.  # noqa: E501
        :type datapoints: List[List]
        """
        self.openapi_types = {
            'datapoints': List[List]
        }

        self.attribute_map = {
            'datapoints': 'datapoints'
        }

        self._datapoints = datapoints

    @classmethod
    def from_dict(cls, dikt) -> 'SpotPricesDatapoints':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SpotPricesDatapoints of this SpotPricesDatapoints.  # noqa: E501
        :rtype: SpotPricesDatapoints
        """
        return util.deserialize_model(dikt, cls)

    @property
    def datapoints(self):
        """Gets the datapoints of this SpotPricesDatapoints.


        :return: The datapoints of this SpotPricesDatapoints.
        :rtype: List[List]
        """
        return self._datapoints

    @datapoints.setter
    def datapoints(self, datapoints):
        """Sets the datapoints of this SpotPricesDatapoints.


        :param datapoints: The datapoints of this SpotPricesDatapoints.
        :type datapoints: List[List]
        """

        self._datapoints = datapoints
