# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from metal.types.base_model_ import Model
from metal import util


class SSHKeyInput(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, label=None, key=None):  # noqa: E501
        """SSHKeyInput - a model defined in OpenAPI

        :param label: The label of this SSHKeyInput.  # noqa: E501
        :type label: str
        :param key: The key of this SSHKeyInput.  # noqa: E501
        :type key: str
        """
        self.openapi_types = {
            'label': str,
            'key': str
        }

        self.attribute_map = {
            'label': 'label',
            'key': 'key'
        }

        self._label = label
        self._key = key

    @classmethod
    def from_dict(cls, dikt) -> 'SSHKeyInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SSHKeyInput of this SSHKeyInput.  # noqa: E501
        :rtype: SSHKeyInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def label(self):
        """Gets the label of this SSHKeyInput.


        :return: The label of this SSHKeyInput.
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this SSHKeyInput.


        :param label: The label of this SSHKeyInput.
        :type label: str
        """

        self._label = label

    @property
    def key(self):
        """Gets the key of this SSHKeyInput.


        :return: The key of this SSHKeyInput.
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this SSHKeyInput.


        :param key: The key of this SSHKeyInput.
        :type key: str
        """

        self._key = key
