# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from metal.types.base_model_ import Model
from metal.types.virtual_circuit import VirtualCircuit
from metal import util

from metal.types.virtual_circuit import VirtualCircuit  # noqa: E501

class VirtualCircuitList(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, virtual_circuits=None):  # noqa: E501
        """VirtualCircuitList - a model defined in OpenAPI

        :param virtual_circuits: The virtual_circuits of this VirtualCircuitList.  # noqa: E501
        :type virtual_circuits: List[VirtualCircuit]
        """
        self.openapi_types = {
            'virtual_circuits': List[VirtualCircuit]
        }

        self.attribute_map = {
            'virtual_circuits': 'virtual_circuits'
        }

        self._virtual_circuits = virtual_circuits

    @classmethod
    def from_dict(cls, dikt) -> 'VirtualCircuitList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VirtualCircuitList of this VirtualCircuitList.  # noqa: E501
        :rtype: VirtualCircuitList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def virtual_circuits(self):
        """Gets the virtual_circuits of this VirtualCircuitList.


        :return: The virtual_circuits of this VirtualCircuitList.
        :rtype: List[VirtualCircuit]
        """
        return self._virtual_circuits

    @virtual_circuits.setter
    def virtual_circuits(self, virtual_circuits):
        """Sets the virtual_circuits of this VirtualCircuitList.


        :param virtual_circuits: The virtual_circuits of this VirtualCircuitList.
        :type virtual_circuits: List[VirtualCircuit]
        """

        self._virtual_circuits = virtual_circuits
