# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from metal.types.base_model_ import Model
from metal.types.meta import Meta
from metal.types.volume import Volume
from metal import util

from metal.types.meta import Meta  # noqa: E501
from metal.types.volume import Volume  # noqa: E501

class VolumeList(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, volumes=None, meta=None):  # noqa: E501
        """VolumeList - a model defined in OpenAPI

        :param volumes: The volumes of this VolumeList.  # noqa: E501
        :type volumes: List[Volume]
        :param meta: The meta of this VolumeList.  # noqa: E501
        :type meta: Meta
        """
        self.openapi_types = {
            'volumes': List[Volume],
            'meta': Meta
        }

        self.attribute_map = {
            'volumes': 'volumes',
            'meta': 'meta'
        }

        self._volumes = volumes
        self._meta = meta

    @classmethod
    def from_dict(cls, dikt) -> 'VolumeList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VolumeList of this VolumeList.  # noqa: E501
        :rtype: VolumeList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def volumes(self):
        """Gets the volumes of this VolumeList.


        :return: The volumes of this VolumeList.
        :rtype: List[Volume]
        """
        return self._volumes

    @volumes.setter
    def volumes(self, volumes):
        """Sets the volumes of this VolumeList.


        :param volumes: The volumes of this VolumeList.
        :type volumes: List[Volume]
        """

        self._volumes = volumes

    @property
    def meta(self):
        """Gets the meta of this VolumeList.


        :return: The meta of this VolumeList.
        :rtype: Meta
        """
        return self._meta

    @meta.setter
    def meta(self, meta):
        """Sets the meta of this VolumeList.


        :param meta: The meta of this VolumeList.
        :type meta: Meta
        """

        self._meta = meta
