=begin
#Metal API

#This is the API for Equinix Metal Product. Interact with your devices, user account, and projects.

The version of the OpenAPI document: 1.0.0
Contact: support@equinixmetal.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.0-SNAPSHOT

=end

require 'cgi'

module OpenapiClient
  class OperatingSystemVersionsApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Retrieve all operating system versions
    # Provides a listing of available operating system versions.
    # @param [Hash] opts the optional parameters
    # @return [Array<OperatingSystem>]
    def find_operating_system_version(opts = {})
      data, _status_code, _headers = find_operating_system_version_with_http_info(opts)
      data
    end

    # Retrieve all operating system versions
    # Provides a listing of available operating system versions.
    # @param [Hash] opts the optional parameters
    # @return [Array<(Array<OperatingSystem>, Integer, Hash)>] Array<OperatingSystem> data, response status code and response headers
    def find_operating_system_version_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: OperatingSystemVersionsApi.find_operating_system_version ...'
      end
      # resource path
      local_var_path = '/operating-system-versions'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Array<OperatingSystem>'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['x_auth_token']

      new_options = opts.merge(
        :operation => :"OperatingSystemVersionsApi.find_operating_system_version",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: OperatingSystemVersionsApi#find_operating_system_version\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
